plugins:
  patreon_creator_enabled:
    default: false
    client: true
  patreon_creator_login_enabled:
    default: false
    client: true
  patreon_creator_client_id:
    default: ''
  patreon_creator_client_secret:
    default: ''
  patreon_creator_discourse_username:
    default: ''
    type: username
  patreon_creator_access_token:
    default: ''
  patreon_creator_refresh_token:
    default: ''
  patreon_creator_nsfw_group:
    default: ''
    type: group
  patreon_creator_max_patreon_api_reqs_per_hr:
    default: 100
  patreon_creator_max_patreon_api_reqs_per_day:
    default: 1000
  patreon_creator_verbose_log:
    default: false
  patreon_creator_login_ignore_state:
    default: false
    hidden: true
  patreon_creator_bypass_creator_regex:
    default: ''
